- name: Checkout
  uses: actions/checkout@v4
- name: SFTP upload
  uses: Dylan700/sftp-upload-action@latest
  with:
    server: alpha.gg-community.de
    username: ${{secrets.FTPUSERNAME}}
    password: ${{secrets.password}}
    port: 2022
    uploads: |
    garrysmod/ => /home/container/garrysmod/

