name: Upload complete repo (e.g. website) to a SFTP destination
on:
  pull_request:
    # For the develop branch only.
    branches:
      - develop
    # Execute the action on closed (merged) PR.
    types:
      [closed]
jobs:
  Upload-to-SFTP:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code # Checkout the latest code
        uses: actions/checkout@v3

      - name: 📂 SFTP uploader # Upload to SFTP
        uses: wangyucode/sftp-upload-action@v2.0.4
        with:
          host: alpha.gg-community.de #${{ secrets.HOST }} # Recommended to put the credentials in github secrets.
          username: ${{secrets.FTPUSERNAME}}
          password: ${{secrets.FTPPASSWORD}}
          port: 2022 # Optional, Default to 22.
          compress: true # Compression
          forceUpload: false # Optional, Force uploading all files, Default to false(upload only newer files).
          localDir: "." # Required, Absolute or relative to cwd.
          remoteDir: "/garrysmod/" # "/home/container/" # Required, Absolute path only.
          exclude: ".git,.github" # Optional. exclude patterns (glob) like .gitignore, use ',' to split, Default to ''.
